<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/06/10
 * Time: 14:22
 */

namespace EShop\Controller;


use Think\Exception;

class ComWrkTaskPlanController extends BaseController{

	protected $_permission_action_name = array('list');

	protected $wrkCompanyId;

	public function _initialize()
	{
		parent::_initialize(); // TODO: Change the autogenerated stub
		$this->wrkCompanyId = session("wrk_company_id");
	}


	/**
	 * 任务列表
	 */
	public function indexAction()
	{
		$this->assign("title","服务通知");

		$this->display();
	}

	/**
	 * 合同任务页
	 */
	public function listAction()
	{
		$postData = I("post.");
		$condition = $this->parseFilter($postData);


		//合同任务列表
		$taskList = D('WrkTaskPlan')->alias('a')
			->field('a.id,a.task_name,a.status,c.name AS company_name,a.update_content,a.update_time')
			->join('LEFT JOIN sys_branch AS c ON c.id = a.company_id')
			->where($condition)
			->order('a.update_time desc')
			->page($postData['page'],20)
			->select();

		foreach ($taskList as $k=>$v){
			$taskList[$k]['update_time'] = $v['update_time'] ? date("Y-m-d",$v['update_time']) : '';
		}
		$this->ajaxReturn($taskList);
	}

	//筛选条件
	protected function parseFilter($postData){
		$condition = [];
		$condition['a.branch_id'] = getBrowseBranchId();
		$condition['a.company_id'] = $this->wrkCompanyId;
		if($postData['state'] != ""){
			$condition['a.status'] = $postData['state'];
		}
		if ($postData['keyword'] != ""){
			$condition['a.task_name'] = 'a.task_name like \'%'.$postData['keyword'].'%\'';
		}
		return $condition;
	}

	/**
	 * 详情
	 */
	public function detailAction()
	{
		$this->assign('title','任务进度');
		$id = I('id');
		$taskInfo = D('WrkTaskPlan')->alias('a')
			->field('a.id,a.leader_id,cu.name as company_name,wa.name as contract_name,wa.sys_sn,wa.attach_group,a.task_name,a.is_to_customer,a.status,cus.name as cus_name,shu.staff_name,shu.mobile,a.evaluation_num,a.evaluation_txt')
			->join('INNER JOIN wrk_agreement as wa on wa.id = a.contract_id')
			->join('INNER JOIN sys_branch as cu on cu.id = a.company_id')
			->join('LEFT JOIN sys_user as shu ON shu.id = a.leader_id')
			->join('LEFT JOIN sys_user_module_setting AS cums ON cums.company_id = a.company_id AND cums.module = "WrkTaskPlan" AND cums.branch_id = a.branch_id AND cums.permit_value = 1 AND cums.type = 0')
			->join('LEFT JOIN sys_user AS cus ON cus.id = cums.user_id')
			->where(array('a.id'=>$id))
			->find();
		$this->assign('model',$taskInfo);
		$this->display();
	}

	/**
	 * 提报进度列表
	 */
	public function scheduleListAction()
	{
		try{
			$page_index = I("page/d", 1);
			$page_size = I("rows/d", 1024);
			$task_plan_id = I('task_plan_id');


			if (empty($task_plan_id)){
				throw new Exception('请选择合同任务');
			}

			$condition['a.task_plan_id'] = array('eq',$task_plan_id);

			$list = D('WrkTaskItem')->alias("a")
				->field("a.id,a.progress_type_name,a.progress_situation,creater.name as create_name,receiver.name as receiver_name,a.is_sure,a.create_type,a.create_time,a.sure_time,a.rejected_time")
				->join('LEFT JOIN sys_user AS creater ON creater.id = a.create_id')
				->join('LEFT JOIN sys_user AS receiver ON receiver.id = a.receiver_id')
				->where($condition)
				->order('a.id DESC')
				->page($page_index, $page_size)
				->select();

			foreach ($list as $key=>$value){
				$list[$key]['create_time'] = $value['create_time'] ? date('Y/m/d',$value['create_time']) : '';
				$list[$key]['sure_time'] = $value['sure_time'] ? date('Y/m/d',$value['sure_time']) : '';
				$list[$key]['rejected_time'] = $value['rejected_time'] ? date('Y/m/d',$value['rejected_time']) : '';
			}

			if (empty($list)){
				throw new Exception('没有更多了');
			}

			$this->ajaxReturn(buildMessage($list));
		} catch (Exception $e) {
			$this->ajaxReturn(buildErrorMessage($e->getMessage()));
		}

	}

	/**
	 * 提报进度详情
	 */
	public function scheduleInfoAction()
	{
		$this->assign('title','进度详情');
		$id = I('id');
		$info = D('WrkTaskItem')->alias('a')
			->field('sh.name as branch_name,wtp.task_name,wtp.attach_group,a.*,khu.name as receiver_name')
			->join('INNER JOIN sys_branch AS sh ON sh.id = a.branch_id')
			->join('INNER JOIN wrk_task_plan AS wtp ON wtp.id = a.task_plan_id')
			->join('LEFT JOIN sys_user AS khu ON khu.id = a.receiver_id')
			->where(array('a.id'=>array('eq',$id)))
			->find();

		$info['sure_time'] = $info['sure_time'] ? $info['sure_time'] : '';
		$info['rejected_time'] = $info['rejected_time'] ? $info['rejected_time'] : '';
		$info['extended_parameter'] = json_decode($info['extended_parameter'],true);
		$info['images'] = json_decode($info['images'],true);
		$info['attachment'] = json_decode($info['attachment'],true);
		$info['rejected_images'] = json_decode($info['rejected_images'],true);
		$info['rejected_attachment'] = json_decode($info['rejected_attachment'],true);

		$this->assign('model',$info);
		$this->display();
	}

	/**
	 * 新增提报进度
	 */
	public function addScheduleAction()
	{
		try{
			$data = I('post.');

			//合同信息
			if (empty($data['contract_id'])){
				throw new Exception('请选择合同');
			}
			$wrkAgreement = M('WrkAgreement')->field('name,sys_sn,is_task_plan')->where(array('id'=>array('eq',$data['contract_id'])))->find();
			if (empty($wrkAgreement)){
				throw new Exception('该合同不存在');
			}
			if ($wrkAgreement['is_task_plan'] == 2){
				throw new Exception('该合同冻结中');
			}
			if ($wrkAgreement['is_task_plan'] == 3){
				throw new Exception('该合同已结束');
			}

			//任务信息
			if (empty($data['task_plan_id'])){
				throw new Exception('请选择任务');
			}
			$wrkTaskPlan = M('WrkTaskPlan')->alias('a')
				->field('a.task_name,a.status,a.leader_id,a.is_to_customer,cu.id as cuser_id')
				->join('LEFT JOIN sys_user_module_setting AS cums ON cums.branch_id = a.branch_id AND cums.company_id = a.company_id AND cums.module = "WrkTaskPlan"  AND cums.permit_value = 1 AND cums.type = 0')
				->join('LEFT JOIN sys_user AS cu ON cu.id = cums.user_id')
				->where(array('a.id'=>array('eq',$data['task_plan_id'])))
				->find();
			if (empty($wrkTaskPlan)){
				throw new Exception('该任务不存在');
			}
			if ($wrkTaskPlan['status'] == 2){
				throw new Exception('该任务冻结中');
			}
			if ($wrkTaskPlan['status'] == 3){
				throw new Exception('该任务已结束');
			}


			$data['create_id'] = $this->userId;
			$data['create_type'] = 2;
			$data['create_time'] = time();
			$data['receiver_id'] = $wrkTaskPlan['leader_id'];
			$data['extended_parameter'] = array();
			if (!empty($data['field'])){
				foreach ($data['field'] as $key=>$value){
					$data['extended_parameter'][] = array('field'=>$data['field'][$key],'value'=>$data['value'][$key]);
				}
			}

			$data['extended_parameter'] = json_encode($data['extended_parameter']);
//			if ($data['images']){
//				$data['images'] = explode(',',trim($data['images'],','));
//			}
			$data['images'] = $_POST['images'];
//			if ($data['attachment']){
//				$data['attachment'] = explode(',',trim($data['attachment'],','));
//			}
			$data['attachment'] = $_POST['attachment'];

			$item = D('WrkTaskItem')->create($data);
			if (!$item){
				throw new Exception(D('WrkTaskItem')->getError());
			}

			$results = D('WrkTaskItem')->add($item,array('callback'=>true));

			//发送给商户通知人
			if (!empty($wrkTaskPlan['notifier_id'])){
				$url = str_replace('shop','shop'.$this->_user_session->currBranchId,SHOP_ROOT).'/WrkTaskPlan/scheduleInfo/id/'.$results;
				send_one_wx_message($wrkTaskPlan['notifier_id'],$url,$data['progress_situation'],$wrkAgreement['sys_sn'],$wrkTaskPlan['task_name']);
			}

			//发送消息给商户负责人
			if (!empty($wrkTaskPlan['leader_id'])){
				$url = str_replace('shop','shop'.$this->_user_session->currBranchId,SHOP_ROOT).'/WrkTaskPlan/scheduleInfo/id/'.$results;
				send_one_wx_message($wrkTaskPlan['notifier_id'],$url,$data['progress_situation'],$wrkAgreement['sys_sn'],$wrkTaskPlan['task_name']);
			}

			$this->ajaxReturn(buildMessage($results));
		} catch (Exception $e) {
			$this->ajaxReturn(buildErrorMessage($e->getMessage()));
		}
	}

	/**
	 * 沟通反馈
	 */
	public function feedbackAction()
	{

		$task_plan_id = I('task_plan_id');
		$agreementInfo = D('WrkAgreement')->alias('a')
			->field('a.id as contract_id,a.branch_id,a.company_id,wtp.attach_group,wtp.id as task_plan_id')
			->join('INNER JOIN sys_branch AS c ON c.id = a.company_id')
			->join('INNER JOIN wrk_task_plan AS wtp ON wtp.contract_id = a.id')
			->join('LEFT JOIN sys_user_module_setting AS cums ON cums.company_id = a.company_id AND cums.module = "WrkTaskPlan" AND cums.branch_id = a.branch_id AND cums.permit_value = 1 AND cums.type = 0')
			->join('LEFT JOIN sys_user AS cu ON cu.id = cums.user_id')
			->where(array('wtp.id'=>$task_plan_id))
			->find();

		$this->assign('model',$agreementInfo);

		$this->display();
	}

	/**
	 * updateSchedule
	 * 确认服务进度
	 */
	public function updateScheduleAction()
	{
		try{
			$id = I('id');

			$info = D('WrkTaskItem')->find($id);
			if (empty($info)){
				throw new Exception('任务进度不存在');
			}

			if ($info['sure_time'] > 0){
				throw new Exception('该服务已被确认！');
			}

			if ($info['rejected_time'] > 0){
				throw new Exception('该服务已被驳回！');
			}

			$userId = $this->userId;
			//是否是合同任务客户负责人
			$isWrkTaskPlan = M('SysUserModuleSetting')
				->where('user_id = '.$userId.' AND company_id = '.$info['company_id'].' AND module = "WrkTaskPlan" AND branch_id = '.$info['branch_id'].' AND permit_value = 1 AND type = 0')
				->find();
			if (empty($isWrkTaskPlan)){
				$customer_leader_id = M('SysBranch')->where(array('id'=>array('eq',$info['company_id'])))->getField('customer_leader_id');
				if ($customer_leader_id != $userId){
					throw new Exception('你无权操作');
				}
			}

			$info['receiver_id'] = $userId;
			$info['sure_time'] = time();
			D('WrkTaskItem')->update($info);

		    $this->ajaxReturn(buildMessage('操作成功'));
		} catch (Exception $e) {
		    $this->ajaxReturn(buildErrorMessage($e->getMessage()));
		}

	}

	public function rejectedAction()
	{
		$id = I('id',0);

		$TaskPlan = M('WrkTaskPlan')->alias('a')
			->field('a.id as task_plan_id,a.attach_group,wti.id as task_item_id')
			->join('INNER JOIN wrk_task_item as wti ON wti.task_plan_id = a.id')
			->where('wti.id = '.$id)
			->find();

		$this->assign('model',$TaskPlan);
		$this->display();
	}

	public function doRejectedAction(){
		try{
			$id = I('task_item_id');

			$info = D('WrkTaskItem')->find($id);
			if (empty($info)){
				throw new Exception('任务进度不存在');
			}

			if ($info['sure_time'] > 0){
				throw new Exception('该服务已被确认！');
			}

			if ($info['rejected_time'] > 0){
				throw new Exception('该服务已被驳回！');
			}

			$userId = $this->userId;
			//是否是合同任务客户负责人
			$isWrkTaskPlan = M('SysUserModuleSetting')
				->where('user_id = '.$userId.' AND company_id = '.$info['company_id'].' AND module = "WrkTaskPlan" AND branch_id = '.$info['branch_id'].' AND permit_value = 1 AND type = 0')
				->find();
			if (empty($isWrkTaskPlan)){
				$customer_leader_id = M('SysBranch')->where(array('id'=>array('eq',$info['company_id'])))->getField('customer_leader_id');
				if ($customer_leader_id != $userId){
					throw new Exception('你无权操作');
				}
			}

			$info['receiver_id'] = $userId;
			$info['is_rejected'] = 1;
			$info['rejected_time'] = time();
			$info['rejected_content'] = I('rejected_content');
			if (I('rejected_content')){
				$info['rejected_images'] = $_POST['rejected_images'];
			}
			if (I('rejected_attachment')){
				$info['rejected_attachment'] = $_POST['rejected_attachment'];
			}
			D('WrkTaskItem')->update($info);

		    $this->ajaxReturn(buildMessage());
		} catch (Exception $e) {
		    $this->ajaxReturn(buildErrorMessage($e->getMessage()));
		}
	}

	public function evaluationAction()
	{
		try{

			$id = I('task_plan_id');

			$info = D('WrkTaskPlan')->find($id);
			if (empty($info)){
				throw new Exception('该服务不存在');
			}

			$userId = $this->userId;
			//是否是合同任务客户负责人
			$isWrkTaskPlan = M('SysUserModuleSetting')
				->where('user_id = '.$userId.' AND company_id = '.$info['company_id'].' AND module = "WrkTaskPlan" AND branch_id = '.$info['branch_id'].' AND permit_value = 1 AND type = 0')
				->find();
			if (empty($isWrkTaskPlan)){
				$cuser = M('SysBranch')->field('customer_leader_id as user_id')->where(array('id'=>array('eq',$info['company_id'])))->find();
				if ($cuser['user_id'] != $userId){
					throw new Exception('你无权操作');
				}
			}

			$info['evaluation_num'] = I('evaluation_num');
			$info['evaluation_txt'] = I('evaluation_txt');

			D("WrkTaskPlan")->save($info);

			$item['contract_id'] = $info['contract_id'];
			$item['task_plan_id'] = $info['id'];
			$item['branch_id'] = $info['branch_id'];
			$item['company_id'] = $info['company_id'];
			$item['create_id'] = $this->userId;
			$item['create_time'] = time();
			$item['create_type'] = 2;
			$item['is_sure'] = 0;
			$item['receiver_id'] = M('SysUserModuleSetting')
				->where(array(
					'branch_id' => array('eq',$item['branch_id']),
					'company_id' => array('eq',$item['company_id']),
					'module' => array('eq','WrkTaskPlan'),
					'permit_value' => array('eq',DAC_PERMIT_VALUE_NOTICER),
					'type' => array('eq',DAC_SETTING_TYPE_CUSTOMER)
				))
				->getField('user_id');
			$item['progress_type_name'] = '服务评价';
			$item['progress_situation'] = '您好！该服务客户已评价。';

			$itemDate = D('WrkTaskItem')->create($item);
			if ($itemDate){
				D('WrkTaskItem')->add($itemDate,array("callback"=>true));
			}

		    $this->ajaxReturn(buildMessage());
		} catch (Exception $e) {
		    $this->ajaxReturn(buildErrorMessage($e->getMessage()));
		}
	}
}