<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/13
 * Time: 17:00
 */

namespace ESAdmin\Model;
use Common\Lib\Model\DataModel;

class ComTweetsModel extends DataModel
{
    protected function _before_insert(&$data, $options)
    {
        parent::_before_insert($data, $options); // TODO: Change the autogenerated stub
        $data['created_at'] = time();
        $data['updated_at'] = time();
    }
    protected function _before_update(&$data, $options)
    {
        parent::_before_update($data, $options); // TODO: Change the autogenerated stub
        $data['updated_at'] = time();
    }
}