<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/6
 * Time: 11:59
 */
namespace ESAdmin\Model;

use Common\Lib\Model\BillModel;

class SysRoutineModel extends BillModel {

    protected function _before_insert(&$data, $options)
    {
        parent::_before_insert($data, $options); // TODO: Change the autogenerated stub
        if($data['tool_manager']){
            $data['tool_manager'] = count($data['tool_manager']) == count($this->toolList()) ? 'all' : implode(',',$data['tool_manager'] );
        }else{
            $data['tool_manager'] = '';
        }
    }
    protected function _before_update(&$data, $options)
    {
        parent::_before_update($data, $options); // TODO: Change the autogenerated stub
        if($data['tool_manager']){
            $data['tool_manager'] = count($data['tool_manager']) == count($this->toolList()) ? 'all' : implode(',',$data['tool_manager'] );
        }else{
            $data['tool_manager'] = '';
        }
    }
    public function toolList(){
        return array(
            'nuclear' => '免费核名',
            'trademarks' => '商标查询',
            'files' => '免费合同'
        );
    }
}