<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/6
 * Time: 11:59
 */
namespace ESAdmin\Model;

use Common\Lib\Model\DataModel;
use Think\Exception;

class ToolNuclearNameModel extends DataModel {
    protected $tableName = 'tool_query';
    protected $_NuclearNameType = 0;
    protected function _options_filter(&$options) {
        $this->addOptionsFilter($options, array("type" => $this->_NuclearNameType));
        parent::_options_filter($options);
    }
    protected function _before_update(&$data, $options)
    {
        parent::_before_update($data, $options); // TODO: Change the autogenerated stub
        if ($data['is_process'] == 1){
            $data['processed_at'] = time();
        }
    }
}