<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/6
 * Time: 11:59
 */
namespace ESAdmin\Model;

use Common\Lib\Model\DataModel;
use Think\Exception;

class ToolEnclosureModel extends DataModel {

    protected $_link = array(
        "Company" => array(
            "join_name" => "LEFT",
            'class_name' => "SysBranch",
            'foreign_key' => 'branch_id',
            'mapping_name' => 'company',
            'mapping_fields' => 'name',
            "mapping_key" => "id"
        )
    );
    protected function _before_insert(&$data, $options)
    {
        parent::_before_insert($data, $options); // TODO: Change the autogenerated stub
        $data['created_at'] = time();
        $data['updated_at'] = time();
        $data['icon'] = '/Application/ESAdmin/Public/images/file_icon.png';
//        if (strpos($data['icon'],'/Upload') === false && strpos($data['icon'],'http') === false){
//            $this->error = '请上传正确的图标!';
//            return false;
//        }
        if (!empty($_FILES)) {
            $uploader = getUploader("encicon/", array('rtf','pdf','jpg','jpeg','png','xls', 'xlsx','doc','docx'));
            $info = $uploader->uploadOne($_FILES["enc_url"]);
            if (!$info) {
                $this->error = '文件上传错误!';
                return false;
            } else {
                $filePath = ltrim($uploader->rootPath, ".") . $info['savepath'] . $info['savename'];
                $data['enc_url'] = $filePath;
            }
        } else {
            $this->error = '文件不能为空!';
            return false;
        }
    }
    protected function _before_update(&$data, $options)
    {
        parent::_before_update($data, $options); // TODO: Change the autogenerated stub
        $data['updated_at'] = time();
        if (!empty($_FILES)) {
            $uploader = getUploader("encicon/", array('xls', 'xlsx'));
            $info = $uploader->uploadOne($_FILES["enc_url"]);
            if ($info) {
                $filePath = ltrim($uploader->rootPath, ".") . $info['savepath'] . $info['savename'];
                $data['enc_url'] = $filePath;
            }
        }
    }
}