<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/6
 * Time: 11:59
 */
namespace ESAdmin\Model;

use Common\Lib\Model\DataModel;

class WxConfigModel extends DataModel {

    protected function _before_insert(&$data, $options)
    {
        parent::_before_insert($data, $options); // TODO: Change the autogenerated stub
        $data['wxpay_open'] = (trim($data['wx_pay_key']) == '' || trim($data['wx_mchid']) == '') ? 0 : $data['wxpay_open'];
        if ($data['wxpay_open'] == 1) {
            D('WrkReceivablesAccount')->createWxAccount();
        }
    }
    protected function _before_update(&$data, $options)
    {
        parent::_before_update($data, $options); // TODO: Change the autogenerated stub
        $data['wxpay_open'] = (trim($data['wx_pay_key']) == '' || trim($data['wx_mchid']) == '') ? 0 : $data['wxpay_open'];
        if ($data['wxpay_open'] == 1) {
            D('WrkReceivablesAccount')->createWxAccount();
        }
    }
}