<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/10/26
 * Time: 9:17
 */

namespace ESAdmin\Controller;

class ComBusinessCardController extends SysUserController{

    public function listAction() {
        $page_index = I("page/d", 1);
        $page_size = I("rows/d", 1024);
        $_order = array();
        $this->_parseOrder($_order);
        $_filter = array();
        $this->_parseFilter($_filter);
        $count = D(CONTROLLER_NAME)->setDacFilter("a")->where($_filter)->count();
        $list = D(CONTROLLER_NAME)->setDacFilter("a")->relation(true)->field("a.*")->where($_filter)->page($page_index, $page_size)->order($_order)->select();
        $this->_before_list($list);
        $result["total"] = $count;
        $result["rows"] = $list;
        header('Content-Type:application/json; charset=utf-8');
        exit(json_encode($result));
    }

    public function _before_list(&$list)
    {
        for($i=0;$i<count($list);$i++){
            $result = M("SysUser")->field('company_name')->where('id='.$list[$i]['id'])->find();
            $list[$i]['company_name']=$result['company_name'];
        }

    }

    protected function _before_detail(&$data) {
        $condition["id"] = $data['id'];
        $list = M("SysUser")->field("company_name")->where($condition)->find();
        $data["company_name"] = $list['company_name'];
    }

    public function downloadAction($id, $name){
        $wechat = getWeChatInstance();
        $qrcode_data = $wechat->getQRCode("inviter_$id","2");
        $img_url = $wechat->getQRUrl($qrcode_data['ticket']);
        $content = file_get_contents($img_url);
        $name = "1-推广二维码".$name . ".jpg";
        \Org\Net\Http::download($name,$name, $content);
    }

    private function setWXQrcode($id){
        //$id = $_SESSION['user_id'];
        $wechat = getWeChatInstance();
        $qrcode_data = $wechat->getQRCode("inviter_$id","2");
        $img_url = $wechat->getQRUrl($qrcode_data['ticket']);
        $this->WxQrcode = $img_url;
        return $this->WxQrcode;
    }

    public function showUserAction($id){
        $this->assign('id',$id);
        $this->display('showUser');
    }

    public function userListAction($id){
        $page_index = I("page/d", 1);
        $page_size = I("rows/d", 1024);
        $branch_id = getBrowseBranchId();
        $list = M("DistributionRelation")->where("inviter_id=$id and branch_id = $branch_id")->order("subscribe_time desc")->page($page_index, $page_size)->select();
        for($i=0;$i<count($list);$i++){
            $list[$i]['subscribe_time'] = date("Y-m-d H:i:s",$list[$i]['subscribe_time']);
        }
        $count = M("DistributionRelation")->where("inviter_id=$id and branch_id = $branch_id")->count();
        $result["total"] = $count;
        $result["rows"] = $list;
        header('Content-Type:application/json; charset=utf-8');
        exit(json_encode($result));
    }

    protected function _before_write($type, &$data)
    {
        parent::_before_write($type, $data); // TODO: Change the autogenerated stub
        if(trim($data['contacts']) != ""){
            $check = '/^0?1[3|4|5|6|7|8][0-9]\d{8}$/';
            if(!preg_match($check,$data['contacts'])){
                $this->responseJSON(buildMessage('请输入正确的联系电话',1));
                exit();
            }
        }
    }
}