<?php
/**
 * @auhor kcg
 * */
namespace ESAdmin\Controller;

use Common\Lib\Controller\DataController;
use ESAdmin\Model\MaterialCenterModel;
/**
 *图文 -- 商户签名
 * */
class MaterialCenterSignatureController extends DataController
{
    const CONTENT_MAX = 2000;

    public function detailAction()
    {
        $data = D(CONTROLLER_NAME)->swicthSignature(getBrowseBranchId());
        $data['content'] = (new MaterialCenterModel())->localImgShow($data['content']);
        return $this->ajaxReturn(['code' => 0, 'data' => $data]);
    }

    public function _before_write($type, &$data)
    {
        parent::_before_write($type, $data); // TODO: Change the autogenerated stub
        if(strlen($data['content']) > self::CONTENT_MAX){
            return $this->ajaxReturn(['code' => 1, 'message' => '图文签名最大' . self::CONTENT_MAX . '个字符']);
        }

        $data['content'] = (new MaterialCenterModel())->localUploadServiceImg($data['content']);
    }
}