<?php

namespace ESAdmin\Controller;

use Common\Lib\Controller\DataController;
use  ESAdmin\Model\MiniConfigModel;

class  MiniConfigController extends DataController {
    public function assignPermissions($controller = CONTROLLER_NAME){
        parent::assignPermissions($controller); // TODO: Change the autogenerated stub
        $model = (new MiniConfigModel)->getConfig();

        $this->assign('model', $model);
    }
}