<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/5
 * Time: 14:43
 */

namespace ESAdmin\Controller;


use Common\Lib\Controller\DataController;

class SpTicketController extends DataController
{
    protected function _before_list(&$list)
    {
        parent::_before_list($list); // TODO: Change the autogenerated stub
        foreach($list as $key=>$val){
            $list[$key]['t_least_cost']        = $val['least_cost'].'元';
            $list[$key]['t_reduce_cost']       = $val['reduce_cost'].'元';
            $list[$key]['ticket_begin_date'] = date('Y/m/d H:i:s',$val['ac_ticket_begin_date']);
            $list[$key]['ticket_end_date']   = date('Y/m/d H:i:s',$val['ac_ticket_end_date']);
            $list[$key]['ac_user_get_limit']    = $val['ac_user_get_limit'].'张';
            $list[$key]['ticket_get_count']  = ($val['at_total'] - $val['at_remain']).'张';
            $list[$key]['get_count']         = ($val['at_total'] - $val['at_remain']);
            $list[$key]['at_total']             = $val['at_total'].'张';
            if($val['ac_is_over'] == 1){
                $list[$key]['view_state']    = 0;//已关闭
            }elseif($val['ac_ticket_begin_date'] > time() && $val['ac_is_over'] == 0){
                $list[$key]['view_state']    = 1;//未开始
            }elseif ($val['ac_ticket_begin_date'] < time() && $val['ac_ticket_end_date'] > time() && $val['ac_is_over'] == 0){
                $list[$key]['view_state']    = 2;//进行中
            }elseif ($val['ac_ticket_end_date'] < time() && $val['ac_is_over'] == 0){
                $list[$key]['view_state']    = 3;//已结束
            } else {
                $list[$key]['view_state']    = 4;//已失效
            }
        }


    }
    //修改界面打开之前
    protected function _before_display_dataview(&$data)
    {
        parent::_before_display_dataview($data); // TODO: Change the autogenerated stub
        $data['ticket_begin_date'] = $data['ac_ticket_begin_date'] > 0 ?
                                     date('Y/m/d H:i:s',$data['ac_ticket_begin_date']):
                                     '';
        $data['ticket_end_date']   = $data['ac_ticket_end_date'] > 0?
                                     date('Y/m/d H:i:s',$data['ac_ticket_end_date']):
                                     '';
        $data['has_receive'] = $data['at_total'] == $data['at_remain'] ? 0 : 1;
        $data['arr_scope'] = explode(',',$data['ac_scope']);
        $data['ticket_get_count']  = ($data['at_total'] - $data['at_remain']).'张';
        $data['ac_user_get_limit']    = $data['ac_user_get_limit'].'张';
        $data['at_total']             = $data['at_total'].'张';
        $data['t_least_cost']        = $data['least_cost'].'元';
        $data['t_reduce_cost']       = $data['reduce_cost'].'元';
        if($data['ac_is_over'] == 1){
            $data['view_state']    = 0;//已关闭
        }elseif($data['ac_ticket_begin_date'] > time() && $data['ac_is_over'] == 0){
            $data['view_state']    = 1;//未开始
        }elseif ($data['ac_ticket_begin_date'] < time() && $data['ac_ticket_end_date'] > time() && $data['ac_is_over'] == 0){
            $data['view_state']    = 2;//进行中
        }elseif ($data['ac_ticket_end_date'] < time() && $data['ac_is_over'] == 0){
            $data['view_state']    = 3;//已结束
        } else {
            $data['view_state']    = 4;//已失效
        }
    }

    protected function _before_write($type, &$data)
    {
        parent::_before_write($type, $data); // TODO: Change the autogenerated stub
        $data['created_at'] = time();
        if (self::ACTION_ADD === $type || self::ACTION_COPY === $type){
            $data['updated_at'] = time();
        }
    }
    /*
     * 获取list需要的数据
     */
    protected function HandleTicketData(&$list)
    {
        D(CONTROLLER_NAME)->HandleTicketData($list);
    }
    public function use_detailAction($id)
    {
//        $sp_ticket_detail = D(CONTROLLER_NAME)->getSpTicketDetail($id);
        $this->assign('id',$id);
        $this->display();
    }
    public function getHaveReceivedListsAction($id)
    {
        $page_index = I("page/d", 1);
        $page_size = I("rows/d", 1024);
        $_order = array();
        $this->_parseOrder($_order);
        $_filter = array();
        $_filter['a.id'] = $id;
        $_filter['user.branch_id'] = getBrowseBranchId();
        $_filter['ts.state'] = ['in',[1,2]];
        $this->_parseFilter($_filter);
        if (isset($_filter['ts.mobile'])) {
            $where['ts.mobile']  = $_filter['ts.mobile'];
            $where['user.name']  = $_filter['ts.mobile'];
            $where['_logic'] = 'or';
            $_filter['_complex'] = $where;
            unset($_filter['ts.mobile']);
        }
        $count = D(CONTROLLER_NAME)
                 ->setDacFilter("a")
                 ->join('inner join sp_ticket_stock as ts on ts.ticket_id = a.id')
                 ->join('inner join sys_user as user on user.mobile = ts.mobile')
                 ->where($_filter)
                 ->count();
        $list = D(CONTROLLER_NAME)
                 ->setDacFilter("a")
                 ->join('inner join sp_ticket_stock as ts on ts.ticket_id = a.id')
                 ->join('inner join sys_user as user on user.mobile = ts.mobile')
                 ->field("ts.id,user.head_pic,user.name as received_name,if(ts.state = 1,'未使用','已使用') as user_state,ts.mobile as received_mobile,get_time as received_time")
                 ->where($_filter)
                 ->page($page_index, $page_size)
                 ->distinct(true)
                 ->order($_order)
                 ->select();
        $this->_before_list($list);
        $result["total"] = $count;
        $result["rows"] = $list;
        header('Content-Type:application/json; charset=utf-8');
        exit(json_encode($result));
    }

}