<?php
/**
 * 新手引导页 管理
 * */
namespace ESAdmin\Controller;

use Common\Lib\Controller\TreeController;

class SysGuideController extends TreeController {
    protected function _parseOrder(&$order) {
        $order = ['sort' => 'ASC', 'update_time' => 'DESC'];
    }

    public function listAction($id = null){
        $_filter = array();
        if ($id) { //传入ID，只有在点击父节点的时候才有值
            $_filter["parent_id"] = intval($id);
        }else{
            $this->_parsefilter($_filter);
            if (empty($_filter)){ //没有传入条件，且id为空，只显示父节点
                $_filter["parent_id"] = intval($id);
            }
        }
        $_order = array("id");
        $this->_parseOrder($_order);
        $list = D(CONTROLLER_NAME)->where($_filter)->order($_order)->select();
        foreach ($list as $key => $value) {
            $list[$key]["state"] = empty($value["child_count"]) ? "opened" : "closed";
        }
        $this->_before_list($list);
        $this->ajaxReturn($list);
    }

    public function clientAction(){
        $parants = D(CONTROLLER_NAME)->where(['parent_id' => 0, 'is_show' => 10])->order(['sort' => 'ASC'])->select();
        if(empty($parants)){
            $this->ajaxReturn([]);
        }

        $ids  = array_column($parants, 'id');
        $child = D(CONTROLLER_NAME)->where(['parent_id' => ['in', $ids], 'is_show' => 10 ])->order(['id' => 'ASC'])->select();
        foreach($child as $item){
           foreach($parants as $key => $parant){
               if($parant['id'] == $item['parent_id']){
                   $parants[$key]['childs'][] = $item;
               }
           }
        }

        $this->ajaxReturn($parants);
    }

    public function _before_detail(&$data){
        $data['parent_id'] = intval($data['parent_id']);
        parent::_before_detail($data); // TODO: Change the autogenerated stub
    }
}
