<?php

namespace ESAdmin\Controller;
use Common\Lib\Controller\DataController;

class ToolTrademarksController extends DataController{

    protected function _before_list(&$list)
    {
        parent::_before_list($list); // TODO: Change the autogenerated stub
        foreach($list as $key=>$val){
            $value = json_decode($val['value'],true);
            $list[$key]['name'] = $value['name'];
            $list[$key]['trade'] = $value['trade'];
        }
    }
    protected function _before_detail(&$data)
    {
        parent::_before_detail($data); // TODO: Change the autogenerated stub
        $value = json_decode($data['value'],true);
        $data['name'] = $value['name'];
        $data['trade'] = $value['trade'];
        if ($data['is_process'] == 1){
            $data['processed_at'] = date('Y年m月d日 H:i',$data['processed_at']);
        }
    }
}
