<?php
/**
 * @auhor kcg
 * */
namespace ESAdmin\Controller;

use Common\Lib\Controller\DataController;
use ESAdmin\Model\VcrBillTemplatesModel;

/**
 *导入配置(单证资料模板)
 * */
class VcrBillTemplatesController extends DataController
{ /**
 * 模板导出
 * @param int $id 要导出的模板
 * */
    public function exportTemplateAction($id = null){
        $id = intval($id);
        if ($id == 0) {
            die;
        }

        $condition["id"] = $id;
        $condition["branch_id"] = ['in', [0, getBrowseBranchId()]];
        $model =  new VcrBillTemplatesModel();
        $data = $model->where($condition)->find();
        if (empty($data)) {
            E('模板不存在!');
        }

        $file_name = $data['name'] . '.xlsx';
        vendor('PHPExcel18.PHPExcel');
        $objPHPExcel = new \PHPExcel();
        $objPHPExcel->setActiveSheetIndex(0);
        $templates = json_decode($data['templates']);
        $fieldName = $model->getTemplates($data['type']);
        foreach($templates as $field => $cols){
            if($data['type'] == VcrBillTemplatesModel::TYPE_STATEMENT_10 && $field == 'mark' && $cols){
                $objPHPExcel->getActiveSheet()->setCellValue($data['income'] . '2', $data['mark']);
                continue;
            }

            $title = $fieldName[$field];
            $title = is_array($title) ? $title[0] : $title;
            $this->setColumn($objPHPExcel, $cols, $title);
        }

        $file_name = iconv('UTF-8', 'GBK//IGNORE', $file_name);
        $this->setExcelHeader($file_name);
        $objWriter = new \PHPExcel_Writer_Excel2007($objPHPExcel);
        $objWriter->save('php://output');
        unset($objWriter);
        unset($objPHPExcel);
    }

    public function indexAction($type = 10){
        $type = intval($type);
        $template = 'index';
        switch ($type) {
            case VcrBillTemplatesModel::TYPE_SELF_OPEN_20 :
                $template = 'self_open';
                break;
        }

        $this->assignPermissions();
        $this->assign('type', $type);
        $this->display($template);
    }

    public function _get_detail_template($record){
        $type = intval(isset($record['type']) ? $record['type'] : I('get.type', 10));
        switch ($type) {
            case VcrBillTemplatesModel::TYPE_STATEMENT_10 :
                $template = 'statement_edit';
                break;
            case VcrBillTemplatesModel::TYPE_SELF_OPEN_20 :
                $template = 'self_open_edit';
                break;
        }

        $this->assign('type', $type);
        return $template;
    }

    public function listAction(){
        $page_index = I("page/d", 1);
        $page_size = I("rows/d", 1024);
        $_filter = array();
        $this->_parseFilter($_filter);
        if ($this->hasRelationCondition($_filter)) { //条件中是否有关联表的查询字段，关联字段查询格式为 q-b*xxx(q:查询模式，b管理部的别名,xxx关联表字段
            $count = D(CONTROLLER_NAME)->where($_filter)->count();
        } else {
            $count = D(CONTROLLER_NAME)->where($_filter)->count();
        }
        $list = D(CONTROLLER_NAME)->where($_filter)->page($page_index, $page_size)->order('branch_id DESC')->select();
        $this->_before_list($list);
        $result["total"] = $count;
        $result["rows"] = $list;
        header('Content-Type:application/json; charset=utf-8');
        exit(json_encode($result));
    }

    public function _before_list(&$list){
        foreach ($list as $key => $data) {
            $templates = json_decode($data['templates'], true);
            unset($list[$key]['templates']);
            foreach ($templates as $field => $val) {
                $list[$key][$field] = $val;
            }
        }
    }

    public function _parsefilter(&$filter){
        $filter['branch_id'] = $this->isAdmin() ? 0 : ['in', [0, getBrowseBranchId()]];
        if ($name = I('post.name')) {
            $filter['name'] = ['like', '%' . $name . '%'];
        }

        $filter['type'] = I('get.type', VcrBillTemplatesModel::TYPE_STATEMENT_10);

        parent::_parsefilter($filter); // TODO: Change the autogenerated stub
    }

    public function _before_detailAction($id = null){

    }

    protected function _getDetailData($id){
        $record = [];
        if ($id) {
            $condition["a.id"] = $id;
            $condition["a.branch_id"] = ['in', [0, getBrowseBranchId()]];
            $record = D(CONTROLLER_NAME)->alias("a")->relation(true)->field("a.*")->where($condition)->find();
        }

        if (!empty($record) && $record['branch_id'] == 0) {
            unset($record['id']);
            define("__FORM_ACTION__", "add");
        } else {
            define("__FORM_ACTION__", "update");
        }

        $this->_before_detail($record);
        return $record;
    }

    public function _before_write($type, &$data){
        parent::_before_write($type, $data); // TODO: Change the autogenerated stub
        $data['branch_id'] = $this->isAdmin() ? 0 : getBrowseBranchId();

        $pregInt = '/^[\d].*$/';
        if (!preg_match($pregInt, $data['start']) || $data['start'] < 1) {
            return $this->ajaxReturn(['code' => 1, 'message' => '数据起始行期望是个大于0的整数']);
        }

        if (($templates = (new VcrBillTemplatesModel())->getTemplates($data['type'])) === false) {
            return $this->ajaxReturn(['code' => 1, 'message' => '模板类型错误，请重新进入添加界面!']);
        }

        $templateData = [];
        foreach ($templates as $field => $val) {
            $attributeLable = is_array($val) ? $val[0] : $val;
            $isEmpty = is_array($val) ? $val[1] == VcrBillTemplatesModel::VALIDATE_REQUIRED : false;
            $templateData[$field] = $this->validateRows($data[$field], $attributeLable, $isEmpty);
            unset($data[$field]);
        }

        $data['templates'] = json_encode($templateData, true);
    }

    public function queryAction(){
        return $this->display('query');
    }

    protected function _getLastData($id){
        $record = array();
        if ($id) {
            $condition["a.id"] = $id;
            $record = D(CONTROLLER_NAME)->alias("a")->relation(true)->field("a.*")->where($condition)->find();
        }
        $this->_before_detail($record);

        return $record;
    }

    private function validateRows($val, $attributeLable, $isEmpty = true){
        if ($isEmpty && empty($val)) {
            return $this->ajaxReturn(['code' => 1, 'message' => $attributeLable . '不能为空']);
        }

        $pregRow = '/^[A-Z]{0,2}$/';
        if (!preg_match($pregRow, $val)) {
            return $this->ajaxReturn(['code' => 1, 'message' => $attributeLable . '期望是大写字母,并且最多2位']);
        }

        return $val;
    }

    private function isAdmin(){
        return $this->_user_session->isAdmin;
    }

    private function setColumn(&$objPHPExcel, $column, $name, $rowIndex = 1){
        if (!empty($column)) {
            $objPHPExcel->getActiveSheet()->getColumnDimension($column)->setWidth(25);
            $objPHPExcel->getActiveSheet()->setCellValue($column . $rowIndex, $name);
        }
    }
}