<?php

namespace ESAdmin\Controller;

use Common\Lib\Controller\DataController;
use Common\Lib\Controller\ComplexDataController;

class  WrkInvoiceController extends ComplexDataController {

    public function _parsefilter(&$filter)
    {
        parent::_parsefilter($filter); // TODO: Change the autogenerated stub
        $state = I("post.state");
        if($state != "" && $state == 0){
            $filter['a.state'] = $state;
        }elseif($state == 1){
            $filter['a.state'] = array("in","1,2");
        }
        $filter['a.creater_id'] = array("neq","");
        $start_time = I("post.start_time");
        $end_time = I("post.end_time");
        if($start_time && $end_time){
            $filter['ag.start_time'] = array(array("egt",strtotime($start_time)),array("elt",strtotime($end_time)));
        }
        $date = I("post.date");
        if($date != "" && $date != 4){
            $tmp = D("WrkInvoicePlan")->getQdrDate($date);
            $filter['latest_invoice_time'] = array(array("egt",$tmp['begin']),array("elt",$tmp['end']));
        }/*elseif($date == ""){
            $tmp = D("WrkInvoicePlan")->getQdrDate(1);
            $filter['latest_invoice_time'] = array(array("egt",$tmp['begin']),array("elt",$tmp['end']));
        }*/
    }

    public function _before_list(&$list)
    {
        parent::_before_list($list); // TODO: Change the autogenerated stub
        foreach ($list as $k=>$v){
            $list[$k]['ag_customer_leader_id'] = M("SysUser")->where("id = ".$v['ag_customer_leader_id'])->getField("name");
            $leader = M("SysUser")->where("id = ".$v['ag_leader_id'])->field("name,staff_name")->find();
            $list[$k]['leader_name'] = $leader['staff_name'] == "" ? $leader['name'] : $leader['staff_name'];
            $list[$k]['plan_day'] = date("Y/m/d",$v['plan_day']);
            $list[$k]['amount_noPaid'] = $v['ag_agreement_money'] - $v['amount_paid'];
            if($list[$k]['amount_noPaid'] < 0 ){
                $list[$k]['amount_noPaid'] = 0;
            }
            $list[$k]['ag_customer'] = M("SysUser")->where("id = ".$v['ag_customer_leader_id'])->getField("name");
            if($v['leader_id'] == ""){
                $list[$k]['ag_service_man'] = M("SysUser")->where("id = ".$v['ag_leader_id'])->getField("name");
            }else{
                $list[$k]['ag_service_man'] = M("SysUser")->where("id = ".$v['leader_id'])->getField("name");
            }
            if($v['state'] == 1 or $v['state'] == 2){
                $list[$k]['balance'] = $v['amount_paid'] - $v['ag_agreement_money'];
            }
            $tmp = D("WrkInvoicePlan")->getCompanyLeader($list[$k]['ag_company_id'],CAJ_BRANCH_INVOICE);
            if($list[$k]['ag_customer_leader_id'] == ""){
                $list[$k]['customer_leader'] = $tmp['customer_leader'];
            }else{
                $list[$k]['customer_leader'] = $list[$k]['ag_customer_leader_id'];
            }
            $list[$k]['recently_invoice_time'] = $v['latest_invoice_time']==""?"":date("Y/m/d",$v['latest_invoice_time']);
            if($v['type'] == 1){
                $list[$k]['detail_id'] = M("WrkInvoicePlanDetail")->where("type = 0 and plan_id = ".$v['id'])->getField("id");
            }
        }
    }

}