<?php

namespace ESAdmin\Controller;

use Common\Lib\Controller\DataController;

class  WrkInvoiceApplyController extends DataController {
    public function _parsefilter(&$filter)
    {
        parent::_parsefilter($filter); // TODO: Change the autogenerated stub
        $filter['a.branch_id'] = $this->_user_session->currBranchId;
        $company_id = $this->_user_session->currBranchId;
        $user_id = $this->_user_session->userId;
        $result = M("SysBranch")->where("id = $company_id")->field("leader_id")->find();
        if($user_id != $result['leader_id']){
            $condition['wip.creater_id'] = $user_id;
            $condition['wip.leader_id'] = $user_id;
            $condition['_string'] = "FIND_IN_SET($user_id, wip.visiblers)";
            $condition['_logic'] = "or";
            $filter['_complex'] = $condition;
        }
    }

    public function _before_list(&$list)
    {
        parent::_before_list($list); // TODO: Change the autogenerated stub
        foreach ($list as $k=>$v){
            $list[$k]['ag_customer'] = M("SysUser")->where("id = ".$v['ag_customer_leader_id'])->getField("name");
            //$list[$k]['ag_service_man'] = M("SysUser")->where("id = ".$v['ag_leader_id'])->getField("name");
            $list[$k]['wip_leader_name'] = M("SysUser")->where("id = ".$v['wip_leader_id'])->getField("name");
            $list[$k]['plan_day'] = date("Y/m/d",$v['plan_day']);
            $list[$k]['amount_noPaid'] = $v['ag_agreement_money'] - $v['amount_paid'];
            if($v['state'] == 1){
                $list[$k]['balance'] = $v['ag_agreement_money'] - $v['amount_paid'];
            }
            $tmp = D("WrkInvoicePlan")->getCompanyLeader($list[$k]['id'],CAJ_BRANCH_INVOICE);
            $list[$k]['customer_leader'] = $tmp['customer_leader'];
            //$data['customer_visiblers'] = $tmp['customer_visiblers'];
        }
    }

    public function _before_detail(&$data)
    {
        parent::_before_detail($data); // TODO: Change the autogenerated stub
        $data['ag_start_time'] = date("Y/m/d",$data['ag_start_time']);
        $data['ag_finish_time'] = date("Y/m/d",$data['ag_finish_time']);
        $data['notify_day'] = date("Y/m/d h:s:i",$data['notify_day']);
        $data['plan_day'] = date("Y/m/d h:s:i",$data['plan_day']);
        $data['ag_customer'] = M("SysUser")->where("id = ".$data['ag_customer_leader_id'])->getField("name");
        //$data['ag_service_man'] = M("SysUser")->where("id = ".$data['ag_leader_id'])->getField("name");
        if($data['ag_customer_leader_id']){
            $data['customer_leader'] = M("SysUser")->where("id = ".$data['ag_customer_leader_id'])->getField("name");
        }else{
            $tmp = D("WrkInvoicePlan")->getCompanyLeader($data['id'],CAJ_BRANCH_INVOICE);
            $data['customer_leader'] = $tmp['customer_leader'];
            $data['customer_visiblers'] = $tmp['customer_visiblers'];
        }
        if($data['wip_leader_id']){
            $data['wip_leader_name'] = M("SysUser")->where("id = ".$data['wip_leader_id'])->getField("name");
        }
        if($data['wip_visiblers']){
            $visiblers = explode(",",$data['wip_visiblers']);
            foreach ($visiblers as $v){
                $name = M("SysUser")->where("id = ".$v)->getField("name");
                $data['wip_visiblers_name'] = $data['wip_visiblers_name'] == "" ? $name : $data['wip_visiblers_name'].",$name";
            }
        }
    }

    public function cancelApplyAction(){
       $id = I("post.id");
       $result = M("WrkInvoicePlanDetail")->where("id = $id")->setField("state",5);
       if($result){
           //发送通知
            D("WrkInvoicePlan")->sendCancelApplyMessage($id);
           $this->ajaxReturn(array("error"=>0,"message"=>"取消成功"));
       }else{
           $this->ajaxReturn(array("error"=>1,"message"=>"取消失败"));
       }
    }

    public function getDetailIdAction(){
        $id = I("post.id");
        $result = M("WrkInvoicePlanDetail")
            ->alias("a")
            ->join("wrk_invoice_plan as b on a.agreement_id = b.agreement_id")
            ->where("a.id = $id")
            ->field("b.type as is_plan,b.id")
            ->find();
        //有计划
        if($result['is_plan'] == 1){
            $condition['plan_id'] = $result['id'];
            $condition['is_invoice'] = 1;//开票开关 开
            $condition['type'] = 0;
            //$condition['state'] = array("neq",100);//已取消
            $id = M("WrkInvoicePlanDetail")->where($condition)->getField("id");
            if($id){
                $this->ajaxReturn(array("code"=>1,"message"=>$id,"1"=>1));
            }else{
                $this->ajaxReturn(array("code"=>2,"message"=>"该合同已取消开票！"));
            }
        }else{
            //无计划
            $this->ajaxReturn(array("code"=>0,"message"=>$result['id'],"2"=>2));
        }
    }

    public function getPlanIdAction(){
        $id = I("post.id");
        $result = M("WrkInvoicePlanDetail a")
            ->join("wrk_invoice_plan as b on a.plan_id = b.id")
            ->where("a.id = $id")
            ->field("b.id,b.type")->find();
        if($result['type'] == 1){
            //有计划
            $this->ajaxReturn(array("code"=>1,"message"=>$result['id']));
        }else{
            //无计划
            $this->ajaxReturn(array("code"=>0,"message"=>$result['id']));
        }
    }
}