<?php
namespace ESAdmin\Controller;

use Common\Lib\Controller\DataController;
use ESAdmin\Model\WxPlatformConfigModel;
use EShop\Model\PlatformModel;
/**
 * @author kcg
 * 第三方平台 配置管理 控制器
 */
class WxPlatformConfigController extends DataController{
    public function assignPermissions($controller = CONTROLLER_NAME){
        parent::assignPermissions($controller); // TODO: Change the autogenerated stub
        $config =  WxPlatformConfigModel::getConfig();
        $this->authorLinkAction();
        $this->assign('model', $config);
    }

    public function addAction(){

    }



    public function authorLinkAction(){
        $config = WxPlatformConfigModel::getConfig();
        if(! $config){
            return false;
        }

        $model = new PlatformModel($config);
        $preAuthCode = $model->getPreAuthCode();
        if(! $preAuthCode){
             $this->assign('url', '预授权吗获取失败!');
            return;
        }

        $url = 'https://mp.weixin.qq.com/safe/bindcomponent?';
        $url .= 'action=bindcomponent&auth_type=3&no_scan=1';
        $url .= '&component_appid=' . $config['appid'];
        $url .= '&pre_auth_code=' . $preAuthCode;
        $url .= '&redirect_uri=' . urlencode('http://yyzs.caisuikx.com/Login/appAuthor');
        $url .= '&auth_type=3';
//        $url .= '&biz_appid=';
        $url .= '#wechat_redirect';

       $this->assign('url', $url);
    }

    public function  authorAction(){
        $data['auth_code'] = I('get.auth_code');
    }
}
