<?php

namespace ESAdmin\Controller;

use Common\Lib\Controller\DataController;

class WxReplyController extends DataController
{
    public function assignPermissions($controller = CONTROLLER_NAME)
    {
        parent::assignPermissions($controller);
        $branchId = getBrowseBranchId();
        $model = D('WxReply');
        $this->assign('attention', $model->findAttentionByBranchId($branchId), $this->_user_session->currBranchName);
        $this->assign('auto', $model->findDefaByBranchId($branchId));
    }

    public function _parsefilter(&$filter)
    {
        parent::_parsefilter($filter); // TODO: Change the autogenerated stub
        $filter['event_type'] = 20;

    }

    public function _before_write($type, &$data)
    {
        parent::_before_write($type, $data); // TODO: Change the autogenerated stub
        if (empty($data['content'])) {
            switch (intval($data['reply_type'])) {
                case 10:
                    $errorMsg = '请输入要发送的文本消息';
                    break;
                default:
                    $errorMsg = '请选择素材';
                    break;
            }

            $this->responseJSON(buildMessage($errorMsg, 1));
        }

        $data['keyword'] = isset($data['keyword']) ? $data['keyword'] : '';
        if ($data['event_type'] == 20 && empty($data['keyword'])) {
            $this->responseJSON(buildMessage('请输入关键字', 1));
        }
    }
}


